### ISSUE TITLE
Thoughts on namespaces

### ISSUE THREAD

**Issue by HuwCampbell** [ambiata/icicle#136]
In Ivory at the moment, one can have facts and/or features with the same name placed into different namespaces. It would be pleasing if when Icicle is integrated we could use the same trick (where exactly this is implemented though is an open question).

This would likely mean that feature lookups would have to be namespace aware, as would features themselves.

por ejemplo:
```toml
namespace = "cake"
[fact.ingredients]
  encoding = "string"
  # uses default namespace
[feature.num_ingredients]
  expression = "feature ingredients ~> count"
  # also uses default namespace
[fact.ingredients]
  encoding = "int"
  namespace = "pies"
[feature.sum_ingredients]
  expression = "feature ingredients ~> sum value"
  # must match above namespace in order to see the fact.
  namespace = "pies"
```

The normal way to separate these would be sub-dictionaries with different top level namespaces. This would make new versions of feeds pretty simple.
