### ISSUE TITLE
Generative dictionaries

### ISSUE THREAD

**Issue by HuwCampbell** [ambiata/icicle#224]
A common aspect in machine learning feature sets is similar features being defined with one or two differences. For example:

``` TOML
[feature.count_biscuits]
  expression = """feature foods ~> filter value = "biscuit" ~> count value"""
[feature.count_cakes]
  expression = """feature foods ~> filter value = "cake" ~> count value"""
```

And so on, this gets overwhelming quickly, and more so if we want each of these foodstuffs to be measured over different time periods.

Therefore, we propose that the dictionary format of Icicle be expanded, such that we can perform substitutions for expressions to make these cross products easier.

I propose group tables, 

``` TOML
[group.foodstuffs]
   val = ["biscuit", "cake"]
   pretty = ["Biscuit", "Cake"]

[feature."${foodstuffs.pretty}"]
  expression = """feature foods ~> filter value = "${foodstuffs.val}" ~> count value"""
```

Here we have two fields in one group, these do not get cross products, but instead allow for a "pretty" name, or other variables which are tied together to be used. The arrays `val` and `pretty` must be the same length.

If one were to have

``` TOML
[group.foodstuffs]
   x = ["biscuit", "cake"]
   y = ["Biscuit", "Cake"]
[group.periods]
   x = ["1 days", "1 weeks", "3 weeks"]
   y =  ["1_day", "1_week", "3_weeks"]

[feature."${foodstuffs.y}_${periods.y}"]
  expression = """feature foods ~> window ${periods.x} ~> filter value = "${foodstuffs.x}" ~> count value"""
```

Then a total of 6 features would be output, with names
`Cake_1_day`, `Cake_1_week`,  `Cake_3_weeks`, `Biscuit_1_day`, `Biscuit_1_week`,  `Biscuit_3_weeks`.
